workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/mlops-pv-classification/pv-defection-classification-docker/local_train_cpu:latest
        env:
        - name: WANDB_API_KEY
          value: 49f0bd035ca4760f03e1c1e2599113b2ed5bce3c