workerPoolSpecs:
    machineSpec:
        # machineType: n1-highmem-8
        machineType: n1-standard-16
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/mlops-pv-classification/pv-defection-classification-docker/train_cpu:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY