name: DVC Workflow

on:
  pull_request:
    branches:
    - '**'

    # paths:
    # - '**/*.dvc'
    # - '.dvc/**'

  # push:
  #   branches:
  #   - '**'
  #   paths:
  #   - '**/*.dvc'
  #   - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip list

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Pull data
      run: |
        dvc pull --no-run-cache

    - name: Check dataset and generate report
      run: |
        python src/pv_defection_classification/utils/dataset_checker.py
        cat data_statistics.md  # Display the report in the PR log

    - name: Setup cml
      uses: iterative/setup-cml@v2

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.CML_REPO_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!