ame: Export Draw.io Diagram

on:
  push:
    paths:
      - 'reports/figures/**/*.drawio'

jobs:
  export_diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Convert Diagram to PNG using Docker
        run: |
          docker run --rm -v $(pwd):/workspace jgraph/drawio:latest \
            -x --export --format png --output /workspace/reports/figures/system_diagram.png /workspace/reports/figures/system_diagram.drawio

      - name: List Files After Conversion
        run: ls -la reports/figures/

      - name: Commit and Push Changes
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/figures/system_diagram.png
          git commit -m "Update system_diagram.png from system_diagram.drawio" || echo "No changes to commit"
          git push