name: Export Diagrams

on:
  push:
    paths:
      - 'reports/figures/**/*.drawio'

jobs:
  export_diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Draw.io Desktop
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          wget https://github.com/jgraph/drawio-desktop/releases/download/v26.0.4/drawio-amd64-26.0.4.deb
          sudo dpkg -i drawio-amd64-26.0.4.deb || sudo apt-get install -f -y

      - name: Export Using CLI
        run: xvfb-run drawio --export --format png --output ./reports/figures/system_diagram.png ./reports/figures/system_diagram.drawio --no-sandbox --disable-gpu

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add reports/figures/system_diagram.png
          git commit -m "Update system_diagram.png" || echo "No changes to commit"
          git push


        