name: Export Draw.io Diagram

on:
  push:
    paths:
      - 'reports/figures/**/*.drawio'

jobs:
  export_diagram:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Convert digramm to png
      uses: Burnett01/actions-drawio@1.2
      with:
        src: reports/figures/system_diagram.drawio
        dest: reports/figures/diagramm.png