name: Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        operating-system: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.13
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip list

      - name: Install dependencies on other OSes
        if: runner.os != 'macOS'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip list


      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m
